server:
  port: 5000
  origin: 'http://localhost:3000'

db:
  host: 'localhost'
  type: 'postgres'
  port: 5432
  username: 'postgres'
  password: 'postgres'
  database: 'postgres'
  synchronize: false
